import {
    CURRENCY_CODE_AMD, CURRENCY_CODE_BTC, CURRENCY_CODE_DOGE, CURRENCY_CODE_FILECOIN, CURRENCY_CODE_RUB,
    CURRENCY_CODE_KGS,
    CURRENCY_CODE_KZT, CURRENCY_CODE_LEO, CURRENCY_CODE_OKB,
    CURRENCY_CODE_USD, CURRENCY_CODE_UZS
} from "~/Model/Currency/currency_codes";

const currencyCodes = [
    CURRENCY_CODE_USD,
    CURRENCY_CODE_KZT,
    CURRENCY_CODE_AMD,
    CURRENCY_CODE_KGS,
    CURRENCY_CODE_RUB,
    CURRENCY_CODE_UZS,
    CURRENCY_CODE_BTC,
    CURRENCY_CODE_DOGE,
    CURRENCY_CODE_LEO,
    CURRENCY_CODE_OKB,
    CURRENCY_CODE_FILECOIN
];

export function currencyGetAllCodes()
{
    return currencyCodes;
}

